extraction:
  cpp:
    prepare:
      packages:
        - libboost-all-dev
        - libyaml-cpp-dev
    configure:
      command:
        - mkdir build
        - cd build
        - cmake ..
        - make -s
