language: objective-c
rvm: system

cache:
  directories:
    - $HOME/Library/Caches/Homebrew
before_cache:
  - brew cleanup

before_install:
  - brew update
install:
  - brew install cmake boost libressl yaml-cpp cvc4/cvc4/cvc4
script:
  - mkdir build && cd build && cmake .. && make install
  - poac --version

matrix:
  fast_finish: true
notifications:
  slack: poacpm:VNE7FkuxYAghHHrEfKaj2V19
