version: 1.0.{build}

branches:
  except:
    - gh-pages

configuration:
  - Debug
  - Release

clone_depth: 1

environment:
  matrix:
    - COMPILER: mingw-w64
      GENERATOR: MinGW Makefiles
      PLATFORM: x64

install:
  - git clone https://github.com/jbeder/yaml-cpp.git
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - dir C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1
  - set PATH=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1;%PATH%
  - cd yaml-cpp && mkdir build && cd build
  - cmake .. -G "%GENERATOR%" -DCMAKE_BUILD_TYPE=%Configuration% -DYAML_CPP_BUILD_TESTS=OFF -DCMAKE_SH=CMAKE_SH-NOTFOUND -DCMAKE_INSTALL_PREFIX=C:\Libraries\
  - cmake --build . --target install
  - dir C:\Libraries\
  - cd ..\..

before_build:
  - mkdir build && cd build
  - cmake .. -G "%GENERATOR%" -DBOOST_ROOT=C:\Libraries\boost_1_67_0
  - cmake --build . --config %Configuration%
  - cd ..

build:
  parallel: true
  verbosity: minimal

notifications:
  - provider: Slack
    incoming_webhook:
      secure: 8Th9f6eSvN/wTVU6h5w9WZGmiKS+uHsl11nHGbR87OKy6/95p6rxiRuzHrJy7MXhanRW4+UqhR1r6C4wqIVDmzJgpRH4iW10mbc2by5sWWo=
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
