version: 1.0.{build}

branches:
  except:
    - gh-pages

image:
  - Visual Studio 2015
  - Visual Studio 2017
  - Visual Studio 2017 Preview
  - Visual Studio 2019 Preview

configuration:
  - Debug
  - Release

clone_depth: 1

environment:
  matrix:
    # Visual Studio
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR_NAME: Visual Studio 15 2017

install:
  - git clone https://github.com/jbeder/yaml-cpp.git
  - cd yaml-cpp
  - mkdir build && cd build
  - cmake .. -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_INSTALL_PREFIX=C:\Libraries\
  - cmake --build . --target install
  - dir C:\Libraries\
  - cd ..

before_build:
  - dir C:\Libraries\boost_1_67_0
  - mkdir build && cd build
  - cmake .. -G "%CMAKE_GENERATOR_NAME%" -DBOOST_ROOT=C:\Libraries\boost_1_67_0
  - cmake --build . --config %Configuration%
  - cd ..

build:
  parallel: true
  verbosity: minimal

notifications:
  - provider: Slack
    incoming_webhook:
      secure: 8Th9f6eSvN/wTVU6h5w9WZGmiKS+uHsl11nHGbR87OKy6/95p6rxiRuzHrJy7MXhanRW4+UqhR1r6C4wqIVDmzJgpRH4iW10mbc2by5sWWo=
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
