version: 2
jobs:
  gcc_7:
    docker:
      - image: matken11235/poac:gcc-7
    steps:
      - checkout
      - run: cmake .
      - run: make
      - run: CTEST_OUTPUT_ON_FAILURE=TRUE make test
      - run: ./src/poac --help
  gcc_8:
    docker:
      - image: matken11235/poac:gcc-8
    steps:
      - checkout
      - run: cmake .
      - run: make
      - run: CTEST_OUTPUT_ON_FAILURE=TRUE make test
      - run: ./src/poac --help
#  clang_5:
#    docker:
#      - image: matken11235/poac:clang-5.0
#    steps:
#      - checkout
#      - run: cmake .
#      - run: make
#      - run: CTEST_OUTPUT_ON_FAILURE=TRUE make test
#      - run: ./src/poac --help
#  clang_6:
#    docker:
#      - image: matken11235/poac:clang-6.0
#    steps:
#      - checkout
#      - run: cmake .
#      - run: make
#      - run: CTEST_OUTPUT_ON_FAILURE=TRUE make test
#      - run: ./src/poac --help


workflows:
  version: 2
  build_and_test:
    jobs:
      # GCC
      - gcc_7
      - gcc_8
      # Clang
#      - clang_5
#      - clang_6

